### ISSUE TITLE
badly parsed links from googleapis.com

### ISSUE THREAD

**Issue by tkowalczyk** [nager/Nager.PublicSuffix#27]
link like this:

`https://storage.googleapis.com/`

![image](https://user-images.githubusercontent.com/1682564/50285785-8ddc3780-045d-11e9-83c4-9f07f52e9d07.png)

`TLD` is not correct

**Comment by tinohager** [comment]
https://publicsuffix.org/list/public_suffix_list.dat -> googleapis.com is a TLD in the public suffix list

**Comment by tkowalczyk** [comment]
but there is no googleapis.com here:
http://data.iana.org/TLD/tlds-alpha-by-domain.txt
so who has right? :)

**Comment by tinohager** [comment]
Check the readme :) -> "The validation rules are load direct from https://publicsuffix.org."
We can discuss if we implement iana,org as well

**Comment by tkowalczyk** [comment]
IMO TLD should be taken from IANA because PublicSuffix is not TLD

**Comment by tinohager** [comment]
IMO?

**Comment by tkowalczyk** [comment]
IMO = in my opinion

**Comment by tinohager** [comment]
okay 👍 the origin of this project was the public suffix project. But i am open to integrate iana.org too

**Comment by MaklaCof** [comment]
You can maybe connect with [this project](https://github.com/luckyrat/domain-public-suffix) and merge both projects.
