### ISSUE TITLE
An Exception inside WebTldRuleProvider.LoadFromUrl() results in a corrupt cache file

### ISSUE THREAD

**Issue by galgolan** [nager/Nager.PublicSuffix#28]
When the HttpClient inside WebTldRuleProvider.LoadFromUrl() throws an exception, it is silently caught and the value "error" is returned.
The caller WebTldRuleProvider.BuildAsync() has not way to know this, and calls _cacheProvider.SetValueAsync() with the "error" as value.

The end result is a DomainParser that is initialized without any indication that something bad happened, but parses domains in the wrong way, as there are no rules in place (for example: amazon.co.uk -> co.uk)

In my opinion the exception inside WebTldRuleProvider.LoadFromUrl() should surface all the way up to the user.

**Comment by tinohager** [comment]
I have optimize this issue in the new version
