### ISSUE TITLE
UriNormalizer checks only for https

### ISSUE THREAD

**Issue by GiannisParaskevopoulos** [nager/Nager.PublicSuffix#30]
i see that in UriNormalizer there is a check:
`            if (!domain.Contains("https://"))
            {
                domain = string.Concat("https://", domain);
}`

This may lead to wrong behavior if the domain starts with "http://".

For instance if i would try to get the details of "http://abc.com", then "https://http://abc.com" would be evaluated which is not a valid uri and would cause it to return null.

Thanks for the library by the way.

**Comment by matmalkowski** [comment]
Since I saw there was a PR that already addressed the issue in one of the commits, is this still relevant? Talking about #32 @tinohager
