### ISSUE TITLE
Wildcard TLDs not handled correctly?

### ISSUE THREAD

**Issue by FlorianHockmann** [nager/Nager.PublicSuffix#38]
I'm getting a `ParseException` for a domain like `[something].compute-1.amazonaws.com` when I call `DomainParser.Get()`.

This seems to be caused by the TLD rule `*.compute-1.amazonaws.com` which contains 4 labels (including the wildcard character) and the domain also contains 4 parts. This results in the `DomainParser` thinking that the domain itself is a TLD due to [this check](https://github.com/tinohager/Nager.PublicSuffix/blob/d58b4e4803e109bc6e7533ed688ac521cabeb077/src/Nager.PublicSuffix/DomainParser.cs#L133):

```c#
//Domain is TLD
if (parts.Count == winningRule.LabelCount)
```

Or does the wildcard actually mean that the full string `[something].compute-1.amazonaws.com` is actually a TLD by itself?

**Comment by tinohager** [comment]
In my view the rule says that `[something].compute-1.amazonaws.com` is the TLD.

**Comment by tinohager** [comment]
I have found this information https://github.com/publicsuffix/list/pull/584

**Comment by FlorianHockmann** [comment]
OK, so it's not a bug in this library, but just a very strange public suffix entry created by the AWS team.
We frequently see DNS requests for hostnames of the form `ec2-[0-255]-[0-255]-[0-255]-[0-255].compute-1.amazonaws.com` and they really don't appear to be TLDs, but I also don't see what could be done here if the AWS team registered that as a wildcard TLD.
