### ISSUE TITLE
Trying to Get domain on  ec2-34-206-8-177.compute-1.amazonaws.com throws exception

### ISSUE THREAD

**Issue by dgstpierre** [nager/Nager.PublicSuffix#39]
Trying to parse to get the domain from ec2-34-206-8-177.compute-1.amazonaws.com and getting an exception.  
Using:
var domainParser = new DomainParser(new FileTldRuleProvider("public_suffix_list.dat");
domainParser.Get("ec2-34-206-8-177.compute-1.amazonaws.com");

The exception is:
throws Exception of type 'Nager.PublicSuffix.ParseException' was thrown.
Unknown domain ec2-34-206-8-177.compute-1.amazonaws.com

"ec2-34-206-8-177.compute-1.amazonaws.com" was returned from a reverse DNS on the IP address.  So it should be valid.

**Comment by agustinradamicfo** [comment]
Hi Guys I'm still having this issue, also with ec2-3-28-82-165.compute-1.amazonaws.com ... was this fix confirmed?
