### ISSUE TITLE
System.FormatException: 'Rule contains empty part'

### ISSUE THREAD

**Issue by darkoudeas** [nager/Nager.PublicSuffix#40]
Hi,

Using the default example provided (Loading data from web change cache config),
in line
WebTldRuleProvider.BuildAsync().GetAwaiter().GetResult(); 

I get the following exception

System.FormatException: 'Rule contains empty part'

This exception was originally thrown at this call stack:
	Nager.PublicSuffix.TldRule.TldRule(string, Nager.PublicSuffix.TldRuleDivision)
	Nager.PublicSuffix.TldRuleParser.ParseRules(System.Collections.Generic.IEnumerable<string>)
	Nager.PublicSuffix.TldRuleParser.ParseRules(string)
	Nager.PublicSuffix.WebTldRuleProvider.BuildAsync()
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	
Thanks for any help,
Dimosthenis

**Comment by tinohager** [comment]
Sorry for the late answer, i have try it but i have no error, is the problem still relevant to you
