### ISSUE TITLE
s3.amazonaws.com throwing  an exception "Domain is a TLD according publicsuffix"

### ISSUE THREAD

**Issue by git37** [nager/Nager.PublicSuffix#41]
s3.amazonaws.com throwing an exception "Domain is a TLD according publicsuffix"

**Comment by tinohager** [comment]
`s3.amazonaws.com` is a `TLD` same as `.com`

**Comment by git37** [comment]
where this info is taken from? in the code?

**Comment by tinohager** [comment]
From the public suffix data source https://publicsuffix.org/list/public_suffix_list.dat
