### ISSUE TITLE
Strong assembly name required

### ISSUE THREAD

**Issue by asm2025** [nager/Nager.PublicSuffix#42]
Good day,
Great work on this project by the way. Thanks.
I have an issue running my code using a reference to the nuget package. It complains about a strong assembly name that is required. An error message says: Could not load file or assembly Nager.PublicSuffix A strongly-named assembly is required. Is there a workaround for this?

**Comment by tinohager** [comment]
If you need the DLL signed then I ask you to sign it yourself. I do not want to deal with this topic at the moment.

**Comment by asm2025** [comment]
OK, thanks
