### ISSUE TITLE
Incorrectly splits the *.blogspot.com

### ISSUE THREAD

**Issue by Havrl** [nager/Nager.PublicSuffix#44]
Any idea, why "sergueiko.blogspot.com" is wrongly split? E.g it gives me:

Domain: sergueiko
Hostname: sergueiko.blogspot.com
SubDomain: null
TLD: blogspot.com

Whereas I'd expect the Domain: "blogspot'.

**Comment by tinohager** [comment]
blogspot.com is listed as a TLD in the https://publicsuffix.org/list/public_suffix_list.dat
