### ISSUE TITLE
ParseException - Domain is a TLD according publicsuffix

### ISSUE THREAD

**Issue by emugerman** [nager/Nager.PublicSuffix#46]
Hi,

When try to parse the following URL:

```C#
string url = "http://instahuddle.en.aptoide.com";
var domainParser = new DomainParser(new WebTldRuleProvider());
var domainName = domainParser.Get(url);
var domain = domainName.RegistrableDomain;
```

The following exception in thrown:

```
((Nager.PublicSuffix.ParseException)ex).ErrorMessage
Domain is a TLD according publicsuffix
```

The url `http://instahuddle.en.aptoide.com` is fine and it should give for `RegistrableDomain` just `aptoide.com`

**Comment by tinohager** [comment]
If you check the domain with the `http://` ?

**Comment by emugerman** [comment]
You meant **without** the `http://`, and yes, it is working, i didn't know that it fails because of the protocol. (the exception should be more clear).

But why not support that code-wise? instead of manually remove the protocol?

**Comment by tinohager** [comment]
I am about to release a new version of the library. There are now fewer exceptions thrown and there is better support for dependency injection.
