### ISSUE TITLE
Feature request - something that tells me whether something is a TLD or not

### ISSUE THREAD

**Issue by dmarlow** [nager/Nager.PublicSuffix#47]
I'd love something like `bool IsTld(string host)` that tells me whether something is a TLD or not. IsValidDomain doesn't quite work for all scenarios.

**Comment by tinohager** [comment]
I am about to release a new version of the library. There are now fewer exceptions thrown and there is better support for dependency injection.

**Comment by dazbradbury** [comment]
Do you mind pointing us to the new method for doing: ```bool IsTld(string host)```?
