### ISSUE TITLE
parsing blogspot.com returns message "Nager.PublicSuffix.ParseException: 'Domain is a TLD according publicsuffix'"

### ISSUE THREAD

**Issue by vtorkalo** [nager/Nager.PublicSuffix#53]
Hi. During parsing of "blogspot.com" i am getting this exception:
'Domain is a TLD according publicsuffix'"
Is this expected? blogspot.com doesn't look as TLD

![image](https://user-images.githubusercontent.com/35605304/148800778-4ac27dc4-84a2-45f7-97eb-c124516b7e9d.png)

**Comment by tinohager** [comment]
![image](https://user-images.githubusercontent.com/8215186/148828289-11625e48-4411-4504-bb91-c1ea9ed4c1c1.png)
the domain is a TLD, it is listed in the public suffix list
