### ISSUE TITLE
Feature request: Use the IHttpClientFactory pattern to enable HttpClient customization

### ISSUE THREAD

**Issue by tmb-dk-hostmaster** [nager/Nager.PublicSuffix#56]
I was looking for a way to set a custom timeout and maybe a retry policy (e.g. Polly) for loading the rules in the WebTldRuleProvider, but there is no such feature. I suggest that the IHttpClientFactory pattern could be implemented there: In that way we can provide our own HttpClient with any customizations that we want.
See: https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-factory

**Comment by tinohager** [comment]
I am about to release a new version of the library. There are now fewer exceptions thrown and there is better support for dependency injection.
