### ISSUE TITLE
Nager.PublicSuffix.ParseException: 'Domain is a TLD according publicsuffix'

### ISSUE THREAD

**Issue by xbaha** [nager/Nager.PublicSuffix#57]
I don't know what is wrong with this domain. I am getting the exception in the title, here is the code to regenerate the error:

```
var url = "https://s3.eu-central-1.amazonaws.com/radiobob.de/standalone-player-parabelritter/index.html";
var domainParser = new DomainParser(new WebTldRuleProvider());
var domainInfo = domainParser.Parse(url);
var RegistrableDomain = domainInfo.RegistrableDomain;
```

**Comment by tinohager** [comment]
The domain is a TLD this is correct

**Comment by tinohager** [comment]
We originally implemented it like this. If we release a new version and change it, we would break the backwards compatibility. But I think when I find time I will change this behaviour.

https://github.com/nager/Nager.PublicSuffix/issues/45

**Comment by xbaha** [comment]
Do you mean to say if the domain has another part before the SubDomain, it'll throw an exception, regardless if it's valid or not?

**Comment by tinohager** [comment]
`http://radiobob.de.s3.eu-central-1.amazonaws.com/standalone-player-parabelritter/index.html`

`radiobob.de` is the Domain
`s3.eu-central-1.amazonaws.com` is the TLD

**Comment by xbaha** [comment]
May I know what is the reason for the exception for the domain I gave you?  

https://s3.eu-central-1.amazonaws.com/radiobob.de/standalone-player-parabelritter/index.html
