### ISSUE TITLE
package .dll not copying to bin with msbuild despite dll.refresh file

### ISSUE THREAD

**Issue by russellsims** [nager/Nager.PublicSuffix#60]
hi, while i know this probably isn't an issue with the package and more an issue with with my set up, i was wondiering whether somebody cleverer than me has any insight into what's happening because i'm at a complete loss.

i recently got a new machine and my ci build that previously built successfully is now failing, i've managed to reproduce the issue with a new project

## step to reproduce
* install visual studio 2022 and visual studio 2022 build tools (literally everything ticked in both installations)
* create new ASP.NET empty web site in c:\development\test
* install `Nager.PublicSuffix via nuget and uninstall `Microsoft.CodeDom.Providers.DotNetCompilerPlatform`
* add a new webform `default.aspx` and add some example code
```
using System;
using System.Web;
using Nager.PublicSuffix;
public partial class _Default : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        var host = HttpContext.Current.Request.Url.Host;
        var fileCache = new FileCacheProvider(cacheFileName: "testpublicsuffixcache.dat");
        var domainParser = new DomainParser(new WebTldRuleProvider(cacheProvider: fileCache));
        var domainInfo = domainParser.Parse(host);
        var regdom = domainInfo.RegistrableDomain;
    }
}
```
* delete everything except `nager.publicsuffix.dll.refresh` in the `/bin` folder
* add `<assemblies><add assembly="netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" /></assemblies>` to `<system.web><compilation>` in web.config
* open cmd and run `"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" "C:\Development\test\test.sln" /verbosity:diagnostic`

[here's the msbuild log](https://github.com/nager/Nager.PublicSuffix/files/13378107/msbuild.log)

thanks

**Comment by russellsims** [comment]
hi tino, thank you for taking the time to respond.

the <system.web> node in my web.config currently looks like this
```
<system.web>
    <compilation debug="true" targetFramework="4.7.2">
      <assemblies>
        <add assembly="netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"/>
      </assemblies>
    </compilation>
    <httpRuntime targetFramework="4.7.2"/>
</system.web>
```

still doesn't build in msbuild, but it builds fine in visual studio.

**Comment by tinohager** [comment]
https://learn.microsoft.com/en-us/answers/questions/854473/build-in-visual-studio-runs-fine-msbuild-fails

**Comment by tinohager** [comment]
or maybe

`dotnet build` instead of msbuild

**Comment by russellsims** [comment]
can't build an "asp.net web site" with dotnet, i get the error 
```
Solution file error MSB4249: Unable to build website project "test". The ASP.NET compiler is only available on the .NET Framework version of MSBuild.
```

the previous, i dont get the error they're talking about. the only error in my build output is missing type error `error CS0246: The type or namespace name 'Nager' could not be found (are you missing a using directive or an assembly reference?)`
