### ISSUE TITLE
eTLD support?

### ISSUE THREAD

**Issue by CRC32EX** [nager/Nager.PublicSuffix#62]
Please support `eTLD+1`, `eTLD` and `TLD` ?

Third-party cookies restrict was started, so `eTLD+1` is important.

I want to distinguish between eTLD and TLD.

|Full Domain|eTLD+1|eTLD|TLD|
|--|--|--|--|
|www.example.com|example.com|com|com|
|www.example.ca.us|example.ca.us|ca.us|us|

**Comment by tinohager** [comment]
It's not currently in the planning stage and I don't really understand the benefits of it yet
