### ISSUE TITLE
Add information on breaking changes in v3

### ISSUE THREAD

**Issue by kiddailey** [nager/Nager.PublicSuffix#63]
Thanks for an immensely helpful and awesome library!

Visual Studio notified me that this package had been updated to 3.0 from 2.4.0.  Because of the major version jump I was particularly interested in making sure the changes didn't break anything.

The readme currently states:

> The current stable development branch V2 can be found [here](https://github.com/nager/Nager.PublicSuffix/tree/v2)
> I am currently working on a new version. This includes some breaking changes.

I was unable to find a changelist or a detail of the breaking changes but from what I can gather, here are some that are obvious:

* netstandard2.1, net6.0 or net8.0 is now required
* Some namespaces have changed (affecting _TldRuleParser_ and _TldRule_)
* IEnumerables _TldRules_ now use _IRuleProvider_
* _DomainInfo_ no longer has _Hostname_
* Can no longer parse rules from a string/embedded resource

Not sure if this is a comprehensive list.  The biggest breaking changes for me are the last two.  So my questions are:

1. Is there a replacement for _Hostname_ or do we need to construct it ourselves?  If so, which properties would make the equivalent?
2. For parsing rules from a string/resource, I assume that an _IRuleProvider_ needs to be created.  Am I correct, and is there already one planned to be included?
3. And lastly, would it be possible to get some information on upgrading from v2, or at least a list of the breaking changes since v3 has already been pushed as a release (vs pre-release) to Nuget? 

Thanks again!

**Comment by tinohager** [comment]
I have tidied up the project and reorganized the code into subfolders. I also made sure that it has better support for dependency injection. 

Often the users did not get along with the exceptions, for example when checking `co.uk` as this is a TLD. The library no longer throws an exception here, instead a DomainInfo is returned without `domain`.

**Comment by tinohager** [comment]
I have added the following information to the readme

**Comment by kiddailey** [comment]
Ah - I totally missed StaticRuleProvider.  Thank you much for the clarification, quick reply and changes!

**Comment by mayerwin** [comment]
What about WebTldRuleProvider? This class is no longer present and it seems there is no equivalent one we can use as a replacement. CachedHttpRuleProvider requires a bunch of arguments.

**Comment by MJLHThomassenHadrian** [comment]
+1, missing upgrade guide / changelog with breaking changes.
