### ISSUE TITLE
.Net Framework 4.8.1 compatibility?

### ISSUE THREAD

**Issue by AachoLoya** [nager/Nager.PublicSuffix#64]
Just tried to update the package to 3.0 but VS is complaining about .net 4.8.1 compatibility? 2.4 is working fine

> Could not install package 'Nager.PublicSuffix 3.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by tinohager** [comment]
The functionality for version 2 and 3 remains the same so my recommendation is to stay on version 2

**Comment by tinohager** [comment]
If you upgrade your project to .NET 8, the new version should work without any problems. Otherwise, I recommend staying with the previous version.

**Comment by tinohager** [comment]
To be honest, I spent about three working days on the changeover. Unfortunately, this time is not covered by project sponsorship. If there is a willingness not only to use the development, but also to support it financially, I would be happy to consider it. At the moment, however, the burden of the customization work is mainly on my side, even in your case where you save yourself the migration.

**Comment by julealgon** [comment]
@tinohager can you elaborate why the library changed from NetStandard2.0 to NetStandard2.1 from v2 to v3?

**Comment by tinohager** [comment]
> @tinohager can you elaborate why the library changed from NetStandard2.0 to NetStandard2.1 from v2 to v3?

NetStandard2.0 support is available again

**Comment by julealgon** [comment]
@tinohager I appreciate your newly released version with NetStandard 2.0 support! 

I was going to get to that depending on your answer (since I only saw a single `.Contains` usage that would break 2.0) but you anticipated it nicely.

We'll be upgrading to v3.2.0 right away 😉
