### ISSUE TITLE
Tlds are now valid domain

### ISSUE THREAD

**Issue by unglaublicherdude** [nager/Nager.PublicSuffix#65]
Hi,
we use your public suffix library for domain parsing. In Version to the IsValidDomain did return false when getting a TLD such as "uk" as input but in V3 it returns true. Can we adjust a setting to get the old behaviour back or is this just a bug?

I wrote a local (on my machine because I did not want to commit it) test to validate the behaviour:
```cs
public async Task ParserTest()
{
    var ruleProvider = new LocalFileRuleProvider("public_suffix_list.dat");
    await ruleProvider.BuildAsync();
    var parser = new DomainParser(ruleProvider);
    Assert.IsFalse(parser.IsValidDomain("uk"));
}
```

As workaround I now do also parse the domain before calling IsValidDomain and return false if `RegistrableDomain` is null.

**Comment by tinohager** [comment]
Hi, a new nuget package is available
