### ISSUE TITLE
Why Some Domains Could Not be Parsed?

### ISSUE THREAD

**Issue by xbaha** [nager/Nager.PublicSuffix#71]
The domains in question: 
"streaklinks.com"
"webflow.io"

i have a list > 100k domains, they all work fine except the above! not sure why these domains could not be parsed.

![streaklinks](https://github.com/nager/Nager.PublicSuffix/assets/10267198/c4d52ffd-61c6-41cb-9541-afa51fbf42dd)

**Comment by tinohager** [comment]
This domains are listed in the psl

![streaklinks](https://github.com/nager/Nager.PublicSuffix/assets/8215186/48cbc3ae-afa5-4e2e-8d22-f4448d00a04a)
![webflow](https://github.com/nager/Nager.PublicSuffix/assets/8215186/9f3d5c48-f668-4f51-b4f6-444b32ce99eb)

**Comment by xbaha** [comment]
so is this normal? knowing that these could be either tlds or a domain, right?

**Comment by tinohager** [comment]
Did you understand that https://publicsuffix.org

**Comment by xbaha** [comment]
I just read it, but webflow.com on its own can be both, TLD and a domain name, it's not like .com which can only be TLD, i think there should be an option to parse it if it does not have a higher level domain.
this makes more sense.

**Comment by tinohager** [comment]
I only apply and evaluate the rules of psl. I don't want to have a basic discussion here about how the public suffix list works.
