### ISSUE TITLE
Replacement for WebTldRuleProvider

### ISSUE THREAD

**Issue by mayerwin** [nager/Nager.PublicSuffix#72]
After upgrading the package to v3, `WebTldRuleProvider` is no longer recognized. It seems there is no equivalent provider we can use as a replacement. `CachedHttpRuleProvider` requires a number of arguments. Can you re-add this provider with default suitable arguments?

**Comment by tinohager** [comment]
`SimpleHttpRuleProvider`?

**Comment by mayerwin** [comment]
There is no caching with this RuleProvider :/.

**Comment by tinohager** [comment]
can you briefly explain to me where you use the library, console application, website...?

**Comment by mayerwin** [comment]
This is with a console application, the goal is to extract the root domain from a URI, just like in the first example shown in the [v2 Readme](https://github.com/nager/Nager.PublicSuffix/blob/v2/README.md#analyze-domain):
```
var domainParser = new DomainParser(new WebTldRuleProvider());

var domainInfo = domainParser.Parse("sub.test.co.uk");
//domainInfo.Domain = "test";
//domainInfo.Hostname = "sub.test.co.uk";
//domainInfo.RegistrableDomain = "test.co.uk";
//domainInfo.SubDomain = "sub";
//domainInfo.TLD = "co.uk";
```

**Comment by tinohager** [comment]
https://github.com/nager/Nager.PublicSuffix/blob/a5e3b21db6f9fc105c95324544edd72ff54972e4/src/Nager.PublicSuffix.TestConsole/Program.cs#L8-L25

**Comment by tinohager** [comment]
With the new version i have optimize this issue

```cs
var httpClient = new HttpClient();
var cacheProvider = new Nager.PublicSuffix.RuleProviders.CacheProviders.LocalFileSystemCacheProvider();
var ruleProvider = new CachedHttpRuleProvider(cacheProvider, httpClient);

await ruleProvider.BuildAsync();

var domainParser = new DomainParser(ruleProvider);
```

**Comment by mayerwin** [comment]
Thanks, since it was use case prominently shown before, assuming indeed a lot of users just took advantage of the earlier one-liner, wouldn't it make sense to still expose a `WebTldRuleProvider` class (at least for retrocompatibility), or maybe add a `SimpleCachedHttpRuleProvider`?

**Comment by tinohager** [comment]
I will include the example in the documentation.
